class ActionTypes { // Cài đặt kiểu action
    FIND_ALL_ITEM = "FIND_ALL_ITEM";
    PAGED_ITEM = "PAGED_ITEM";
    FIND_SINGLE_ITEM = "FIND_SINGLE_ITEM";
    FIND_SINGLE_ITEM_BY_IDC = "FIND_SINGLE_ITEM_BY_IDC";
    ADD_ITEM = "ADD_ITEM";
    UPDATE_ITEM = "UPDATE_ITEM";
    REMOVE_ITEM = "REMOVE_ITEM";
    INCREASE_ITEM = "INCREASE_ITEM";
    DECREASE_ITEM = "DECREASE_ITEM";

    SELECT_ITEM = "SELECT_ITEM";
    CHECK_EXISTS = "CHECK_EXISTS";
    SEARCH_BY_EXPAND = "SEARCH_BY_EXPAND";
    SHOW_ALL_ITEM = "SHOW_ALL_ITEM";
    SHOW_PAGED_ITEM = "SHOW_PAGED_ITEM";
    SHOW_SINGLE_ITEM = "SHOW_SINGLE_ITEM";
};

export default new ActionTypes();